defaults:
  - default
  - tokenizer: base_tokenizer
  - tokenizer_trainer: base_tokenizer_trainer
  - data: base_data
  - model: base_model
  - optimizer: base_optimizer
  - optimizer/scheduler: base_scheduler
  - trainer: base_trainer
  - logger: base_logger
